spring.data.mongodb.database=movies
spring.data.mongodb.uri=mongodb+srv://valar:mango%4006@movieapi.pcdtylu.mongodb.net/movies?retryWrites=true&w=majority&authSource=admin

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# API docs path
springdoc.api-docs.path=/api-docs

# Show actuator endpoints (optional)
springdoc.show-actuator=false